# Generated by Django 5.0.4 on 2024-05-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0003_alter_historicalperformance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
